drop table if exists TEMPORALS;

create table TEMPORALS (
	ID				BIGINT PRIMARY KEY,
	LOCAL_DATE		DATE NULL,
	LOCAL_TIME		TIME NULL,
	INSTANT_TS		TIMESTAMP NULL,
	ZONE_ID			VARCHAR(100),
	ZONE_OFFSET		VARCHAR(50)
);
